"use client";

import Chip from "@/components/Chip";
import Image from "next/image";
import { motion } from "framer-motion";
import BottomDecoration from "@/components/BottomDecoration";

export default function Tokenomics() {
  return (
    <div className=" pb-28 -mx-5 md:-mx-12 px-5 relative md:px-12 bg-[#DCDCDC]">
      <div className="max-w-[1440px] mx-auto">
        <motion.h2
          initial={{ opacity: 0, y: 100 }}
          whileInView={{ opacity: 1, y: 0 }}
          transition={{ duration: 0.5, delay: 0.5 }}
          className="font-bold text-5xl md:text-6xl pt-16 text-center text-black"
        >
          Tokenomic
        </motion.h2>
        <motion.svg
          initial={{ opacity: 0 }}
          whileInView={{ opacity: 1, y: 0 }}
          transition={{ duration: 0.2, delay: 1 }}
          xmlns="http://www.w3.org/2000/svg"
          width="125"
          height="4"
          viewBox="0 0 125 4"
          fill="none"
          className="mx-auto mt-4"
        >
          <path
            d="M125 0H0V1.5H29L39 3.5H87.5L96.5 1.5H125V0Z"
            fill="#000000"
          />
        </motion.svg>
        <div className="flex max-lg:flex-col gap-6 items-center mt-16 text-black ">
          <Image
            alt="chart 1"
            width={463}
            height={360}
            src={"/chart1.png"}
            className="max-xl:max-w-sm max-sm:max-w-xs"
          />
          <div>
            <h3 className="font-bold text-3xl">Use of Funds</h3>
            <h4 className="font-bold text-xl mt-8">
              Deinflation (Burning) System
            </h4>
            <p className="text-xl font-light">
              Revenue Sharing and Buyback: In this system, a portion of the
              project&apos;s revenue is used to buy back and burn tokens from
              the market. The revenue can come from various sources, such as
              fees generated by the platform, profits from services, or other
              income streams. By using these funds to repurchase and burn
              tokens, the project reduces the token supply, potentially
              increasing token value.we are uses 25% of profits to buy back and
              burn every quarter. Community-Driven Burning: This would be done
              through voting or governance mechanisms, where token holders have
              the power to propose and approve token burning events. By
              involving the community, projects can ensure transparency and
              alignment of interests among token holders.
            </p>
            <Image
              className="mt-10 w-full"
              width={783}
              height={6}
              alt=""
              src={"/vector 1.png"}
            />
          </div>
        </div>
        <div className="mx-auto">
          <div className="mt-16 md:mt-32 flex max-md:flex-col justify-center">
            <motion.ul
              layout
              initial="hidden"
              whileInView={"visible"}
              viewport={{ once: true }}
              variants={container}
              className="flex flex-col gap-y-5 items-center"
            >
              {LEFT.map((props, i) => (
                <motion.div key={i} variants={item}>
                  <Chip {...props} />
                </motion.div>
              ))}
            </motion.ul>
            <Image
              src={"/gap.png"}
              alt="divider"
              width={6}
              height={166}
              className="h-full mx-16 max-md:hidden"
            />
            <motion.ul
              layout
              initial="hidden"
              whileInView={"visible"}
              viewport={{ once: true }}
              variants={container}
              className="flex flex-col gap-y-5 items-center max-md:mt-5"
            >
              {RIGHT.map((props, i) => (
                <motion.div key={i} variants={item}>
                  <Chip {...props} />
                </motion.div>
              ))}
            </motion.ul>
          </div>
          <div className="col-span-2 flex justify-center items-center mt-5 md:mt-7">
            <Chip color="#0080B3" text="Operational Expenses" />
          </div>
        </div>
      </div>

      {/* details  */}
      <BottomDecoration color="black" />

      {/* small details  */}
      <img src="/b.png" alt="b" className="absolute top-0 left-2 md:left-20" />
    </div>
  );
}

const container = {
  hidden: {
    opacity: 0,
  },
  visible: {
    opacity: 1,
    transition: {
      delayChildren: 0.5,
      staggerChildren: 0.2,
    },
  },
};

const item = {
  hidden: {
    y: 20,
    opacity: 0,
  },
  visible: {
    y: 0,
    opacity: 1,
  },
};

const LEFT = [
  { text: "Partnerships and Acquisitions", color: "#5271FF" },
  { text: "Community Development", color: "#00C2CB" },
];

const RIGHT = [
  { text: "Research and Development", color: "#B34000" },
  { text: "Marketing and Promotion", color: "#FEBD59" },
];
